export default {
	ordinalNum:{
		1: '1st',
		2: '2nd',
		3: '3rd',
		4: '4th',
		5: '5th',
	},
	afsc1: {
		"1":"1X - OPERATIONS",
		"2":"2X - LOGISTICS",
		"3":"3X - SUPPORT",
		"4":"4X - MEDICAL",
		"5":"5X - PROFESSIONAL",
		"6":"6X - ACQUISITION",
		"7":"7X - SPECIAL INVEST.",
		"8":"8X - SPECIAL DUTY ID.",
		"9":"9X - REPORTING ID.",
		"0":"MISSING AFSC"
	},
	majFormat : {
		"** ERROR **":"UNKOWN",
		"**":"UNKOWN",	
		" ":"UNKNOWN",
		"02":"AFIA",
		"03":"AFOTEC",
		"04":"AFCOMM AG",
		"05":"AFIAA",
		"06":"AFAA",
		"07":"AFOSI",
		"08":"HQ AFSFC",
		"09":"AFPC",
		"0B":"US AFA",
		"0D":"USAFE",
		"0J":"AETC",
		"0M":"AFR",
		"0N":"HQ USAF",
		"0R":"PACAF",
		"0V":"AFSOC",
		"11":"AF MPA",
		"12":"AF PA AGY",
		"13":"HQAF SUP AGY",
		"14":"INSTAL CONTR",
		"15":"CIV ENG CNTR",
		"16":"MORT AFRS OP",
		"17":"INSTAL MSM S",
		"18":"DEF HLTH AGY",
		"1A":"AF C2ISRC",
		"1B":"AF MAA",
		"1C":"ACC",
		"1G":"HQ AFLMA",
		"1K":"AF CYBER CMD",
		"1L":"AMC",
		"1M":"AFMC",
		"1P":"AF RL PR AGY",
		"1Q":"HQ AFFSA",
		"1R":"AFRICA CMD",
		"1S":"AFSPC",
		"1W":"AFCESA",
		"1Y":"AFCCT",
		"20":"AF AGY MOD/S",
		"21":"AF NWA",
		"23":"AFELM OSIA(H",
		"24":"HQ USAF DSE",
		"25":"AFWSE",
		"26":"AFBMDO",
		"27":"AFAM-S",
		"28":"AF COM-INFO",
		"29":"AF NAT SEC E",
		"2A":"AFCAA",
		"2B":"AFOC",
		"2D":"AFPOA",
		"2E":"AFLSA",
		"2F":"HQ AFMSA",
		"2G":"AFNA",
		"2H":"AFOG",
		"2I":"ANGRC",
		"2K":"AF HRA",
		"2L":"AF TAC",
		"2M":"AF RBO",
		"2N":"AF CSA",
		"2Q":"HQ AFWA",
		"2R":"AFPEO",
		"2S":"AFELM NORAD",
		"2T":"AF SAFE CTR",
		"2U":"AF SVR AGY",
		"2V":"AFBDA",
		"2W":"11TH WG",
		"2X":"AFREA",
		"2Y":"AFPCA",
		"2Z":"HQ AFMOA",
		"30":"AFELM DISA",
		"31":"AFELM DFAS",
		"32":"ANG - FTS",
		"33":"AFELM DLA",
		"34":"ANG - MOB",
		"35":"AFELM DIA",
		"36":"AFELM NIMA",
		"37":"DEF TR AGY",
		"38":"AFELM JCS",
		"39":"AFELM OSD FA",
		"3A":"CMA",
		"3B":"DEF MEDIA AC",
		"3C":"USCENTCOM",
		"3D":"USSOCOM",
		"3G":"AFELM NATO",
		"3I":"RES. CM",
		"3K":"USEUCOM",
		"3L":"CTR AF HIST",
		"3M":"USSOUTHCOM",
		"3N":"USJFCOM",
		"3O":"USPACOM",
		"3P":"CNTRINTEL FA",
		"3Q":"USSTRATCOM",
		"3S":"USSPACECOM",
		"3T":"USTRANSCOM",
		"3V":"AFELM (OTH)",
		"3W":"AFCEE",
		"3Y":"AF FMA",
		"3Z":"JSSEREA",
		"40":"NAT AIR INTL",
		"41":"AFELM NGA",
		"4C":"AFELM CYBER CM",
		"4D":"AFELM NORTHCOM",
		"4L":"FUTURE FINAN",
		"4V":"NON-DOD/OTHE",
		"4W":"AF DIST WASH",
		"5J":"AF FSC",
		"5K":"AF PETRO AGY",
		"77":"ARM",
		"87":"DEC",
		"99":"USARC",
		"GS":"GLOBAL STRKE",
		"YY":"N/A"
	},
	mpfFormat: {
		"**":"UNKNOWN",
		"A2":"MONTGOMERY",
		"A3":"BIRMINGHAM SHUTTL",
		"A4":"JB ELMENDORF-RICH",
		"A5":"PHOENIX SKY HARBO",
		"A6":"TUCSON",
		"A7":"LITTLE ROCK",
		"A8":"FORT SMITH",
		"A9":"EIELSON",
		"AM":"ALTUS",
		"AT":"ANDERSEN",
		"AU":"JB ANDREWS",
		"AY":"AVIANO",
		"B1":"BEALE",
		"B2":"FRESNO",
		"B3":"MOFFETT",
		"B4":"MARCH",
		"B5":"CHANNEL ISLANDS",
		"B6":"BUCKLEY",
		"B7":"E GRANBY",
		"B8":"NEW CASTLE",
		"B9":"JB ANDREWS",
		"BB":"BARKSDALE",
		"BD":"BEALE",
		"BP":"BOLLING",
		"BU":"BUCKLEY",
		"C2":"JACKSONVILLE",
		"C3":"ROBINS",
		"C4":"SAVANNAH HILTON",
		"C5":"JB PRL HBR-HICKAM",
		"C6":"BOISE AIR TERMINA",
		"C7":"SCOTT",
		"C8":"ABRAHAM LINCOLN C",
		"C9":"GENERAL DOWNING P",
		"CD":"CANNON",
		"CL":"JB CHARLESTON",
		"CO":"COLUMBUS",
		"D2":"TERRE HAUTE",
		"D3":"FORT WAYNE",
		"D4":"DES MOINES",
		"D5":"SIOUX GATEWAY",
		"D6":"MC CONNELL",
		"D7":"FORBES FIELD",
		"D8":"LOUISVILLE",
		"D9":"NEW ORLEANS",
		"DF":"DAVIS-MONTHAN",
		"DM":"DOVER",
		"DW":"DYESS",
		"E2":"BANGOR",
		"E3":"MARTIN STATE",
		"E5":"OTIS",
		"E7":"WESTFIELD BARNES",
		"E8":"W K KELLOGG",
		"E9":"SELFRIDGE",
		"EB":"EDWARDS",
		"ED":"EGLIN",
		"EE":"HURLBURT FIELD",
		"EH":"EIELSON",
		"EJ":"ELLSWORTH",
		"EL":"JB ELMENDORF-RICH",
		"EP":"PETERSON",
		"F3":"MINNEAPOLIS ST PA",
		"F4":"DULUTH",
		"F6":"JACKSON EVERS",
		"F7":"KEY FIELD",
		"F8":"WHITEMAN",
		"FC":"FAIRCHILD",
		"FD":"SCHRIEVER",
		"FT":"FT GEORGE MEADE",
		"FW":"F E WARREN",
		"G1":"ANDERSEN",
		"G2":"ROSECRANS MEM",
		"G3":"GREAT FALLS",
		"G4":"LINCOLN",
		"G5":"RENO TAHOE",
		"G6":"PEASE",
		"G7":"JBMDL MCGUIRE",
		"G8":"ATLANTIC CITY MUN",
		"GF":"GOODFELLOW",
		"GM":"GRAND FORKS",
		"H2":"KIRTLAND",
		"H3":"STEWART",
		"H4":"FRANCIS S GABRESK",
		"H6":"NIAGARA FALLS",
		"H7":"HANCOCK",
		"H8":"SCHENECTADY",
		"H9":"CHARLOTTE DOUGLAS",
		"HH":"PENTAGON",
		"HL":"JB PRL HBR-HICKAM",
		"HN":"FT SAM HOUSTON",
		"HP":"HILL",
		"HS":"HOLLOMAN",
		"IN":"INCIRLIK",
		"J2":"HECTOR",
		"J3":"RICKENBACKER",
		"J4":"SPRINGFIELD BKLY",
		"J6":"MANSFIELD LAHM",
		"J7":"TOLEDO EXPRESS",
		"J9":"WILL ROGERS WORLD",
		"K1":"KLAMATH FALLS",
		"K2":"TULSA",
		"K3":"PORTLAND",
		"K4":"HARRISBURG",
		"K6":"HORSHAM",
		"K7":"PITTSBURGH MONROE",
		"K8":"LUIS MUNOZ MARIN",
		"K9":"QUONSET STATE",
		"KB":"KADENA",
		"KF":"KEESLER",
		"KU":"KUNSAN",
		"KV":"KIRTLAND",
		"L2":"MC ENTIRE",
		"L3":"JOE FOSS",
		"L4":"NASHVILLE",
		"L5":"MEMPHIS",
		"L6":"MC GHEE TYSON",
		"L7":"JBSA KELLY",
		"L8":"FORT WORTH",
		"L9":"ELLINGTON",
		"LA":"JBSA LACKLAND",
		"LD":"LAKENHEATH",
		"LE":"JB LANGLEY-EUSTIS",
		"LJ":"LAUGHLIN",
		"LK":"HANSCOM",
		"LL":"LACKLAND",
		"LP":"LITTLE ROCK",
		"LU":"LOS ANGELES",
		"LY":"LUKE",
		"M2":"SALT LAKE CITY",
		"M3":"BURLINGTON",
		"M4":"JB LANGLEY-EUSTIS",
		"M5":"FAIRCHILD",
		"M6":"CP MURRAY",
		"M7":"YEAGER",
		"M8":"E WV REG SHEPHERD",
		"M9":"DANE CO REGIONAL",
		"MA":"MACDILL",
		"MB":"MALMSTROM",
		"MG":"MAXWELL",
		"MH":"JBLM MCCHORD",
		"MK":"MC CONNELL",
		"ML":"MILDENHALL",
		"MN":"JBMDL MCGUIRE",
		"MO":"MISAWA",
		"MP":"MINOT",
		"MT":"MOODY",
		"MW":"MOUNTAIN HOME",
		"N2":"GEN B MITCHELL",
		"N3":"CHEYENNE ANG",
		"NJ":"NELLIS",
		"OD":"OFFUTT",
		"OP":"OSAN AB",
		"PE":"STUTTGART VAIHING",
		"PF":"PATRICK",
		"PV":"POPE",
		"R1":"ROBINS",
		"R2":"MC CONNELL",
		"R5":"JBSA LACKLAND",
		"R6":"LUKE",
		"R8":"WHITEMAN",
		"R9":"DOBBINS",
		"RF":"RAMSTEIN",
		"RJ":"JBSA RANDOLPH",
		"RX":"ROBINS",
		"S2":"SEYMOUR JOHNSON",
		"S3":"JB ANDREWS",
		"S4":"FORT WORTH",
		"S6":"JBSA RANDOLPH",
		"S7":"AIR RESERVE PERSONNEL CENTER",
		"SF":"SCOTT",
		"SM":"SEYMOUR JOHNSON",
		"SP":"SHAW",
		"SQ":"SHEPPARD",
		"ST":"SPANGDAHLEM",
		"T2":"JBLM MCCHORD",
		"T3":"JBMDL MCGUIRE",
		"T4":"DOVER",
		"T5":"JB CHARLESTON",
		"T6":"SCOTT",
		"T7":"MAXWELL",
		"T8":"TRAVIS",
		"T9":"YOUNGSTOWN WARREN",
		"TE":"TINKER",
		"TP":"TRAVIS",
		"TX":"TYNDALL",
		"U1":"PATRICK",
		"U2":"GRISSOM",
		"U3":"HOMESTEAD",
		"U4":"MARCH",
		"U5":"NIAGARA FALLS",
		"U6":"BARKSDALE",
		"U7":"TINKER",
		"U8":"BEALE",
		"U9":"HILL",
		"US":"USAF ACADEMY",
		"V1":"POPE",
		"V2":"MACDILL",
		"V3":"JB ELMENDORF-RICH",
		"V4":"SCHRIEVER",
		"V5":"NELLIS",
		"V6":"LITTLE ROCK",
		"VH":"VANCE",
		"VQ":"VANDENBERG",
		"W1":"PITTSBURGH",
		"W3":"MINNEAPOLIS",
		"W5":"WESTOVER",
		"W6":"DUKE",
		"W7":"KEESLER",
		"W8":"PETERSON",
		"W9":"WRIGHT PATTERSON",
		"WE":"WRIGHT PATTERSON",
		"WG":"RKB-QUANTICO",
		"WT":"WHITEMAN",
		"YM":"YOKOTA",
		"ZB":"LACKLAND BMTS",
		"ZE":"USAF ACADEMY"
		},
	afscGroupFormat : {
		"1":"PENDING UPDATE",
		"2":"PENDING UPDATE",
		"3":"ABM",
		"4":"ACQUISITION",
		"5":"AEROSPACE MED",
		"6":"BIOMEDICAL",
		"7":"CHAP",
		"8":"DENTAL",
		"9":"HEALTH SVC",
		"10":"JAG",
		"11":"LOGISTICS",
		"12":"MEDICAL",
		"13":"MEDICAL CC",
		"14":"MSN SPT",
		"15":"NAV",
		"16":"NROPS",
		"17":"NURSE",
		"18":"OPERATIONS",
		"19":"OPERATIONS CC",
		"20":"PHYSICIAN",
		"21":"PILOT",
		"22":"PROFESSIONAL",
		"23":"REPORTING IDENTIFIERS",
		"24":"RI",
		"25":"RPA",
		"26":"SDI",
		"27":"SPECIAL DUTY IDENTIFIERS",
		"28":"SPECIAL INVESTIGATIONS",
		"29":"SUPPORT",
		"30":"SURGERY"
	},
	gradeFormat : {
        "01": "[01-02] LT",
        "02": "[01-02] LT",
        "03": "CPT",
        "04": "MAJ",
        "05": "LTC",
        "06": "COL",
        "07": "BGEN",
        "31": "[31-33] AMN",
        "32": "[31-33] AMN",
        "33": "[31-33] AMN",
        "34": "SRA",
        "35": "SSG",
        "E5": "SSG",
        "36": "TSG",
        "E6": "TSG",
        "37": "MSG",
        "E7": "MSG",
        "38": "SMS",
        "E8": "SMS",
        "e8": "SMS", //temporary fix for enlisted promotions
        "39": "CMS",
        "E9": "CMS",
        "51": "EXEC",
        "52": "GS-02",
        "53": "GS-03",
        "54": "GS-04",
        "55": "GS-05",
        "56": "GS-06",
        "57": "GS-07",
        "58": "GS-08",
        "59": "GS-09",
        "60": "GS-10",
        "61": "GS-11",
        "62": "GS-12",
        "63": "GS-13",
        "64": "GS-14",
        "65": "GS-15",
        "66": "NSPS-02",
        "67": "WAGE GROUP"
    }
    ,gradeOrder : {
	    "BGEN": 18,
	    "COL": 17,
	    "LTC": 16,
	    "MAJ": 15,
	    "CPT": 14,
	    "1LT": 13,
	    "2LT": 12,
	    "[01-02] LT": 11,
	    "CMS": 10,
	    "SMS": 9,
	    "MSG": 8,
	    "TSG": 7,
	    "SSG": 6,
	    "SRA": 5,
	    "A1C": 4,
	    "AMN": 3,
	    "AB": 2,
	    "[31-33] AMN": 1,
	}
}
